atomic_swap_contract_address = "0x0383B2965Bfaf5516993C87eB9CF1b1AA646Ae4f"
# You can use `ganache` to run a local Ethereum node
ethereum_ws_rpc_url          = "wss://127.0.0.1:8545"

[swap_params]
sats_to_swap           = 125000
gwei_to_swap           = 2500000
bitcoin_csv_delay      = 8    # 80 minutes MUST be greater than ethereum_timelock_secs
ethereum_timelock_secs = 3600 # 60 minutes MUST be less than bitcoin_csv_delay

[bitcoin_rpc]
# You can use `nigiri` to run a local Bitcoin regtest node
url     = "http://127.0.0.1:18443"
auth    = { username = "admin1", password = "123" }
network = "regtest"

[circom]
witnes_calculator_path = "./atomic_swap.dev/atomic_swap.wasm"
proving_key_path = "./atomic_swap.dev/circuit_final.zkey"
verification_key_path = "./atomic_swap.dev/verification_key.json"

[alice]
satothis_to_send     = 125000
bitcoin_private_key  = "dbf0d0e35b10578d001e3560946a40a5da79d24004b91685dd4eae947d435741"
ethereum_private_key = "7319e149ff5ae8c0993261ef7d93c40c45dade4eb34c3ca20ba49260e9043a55"

[bob]
gwei_to_send          = 2500000
bitcoin_private_key  = "227217f135a31615788fc6f96ebf48c305f41f8d25037b816171de6e4c8fe4f7"
ethereum_private_key = "2d831c8af153f5fa626c19aa051ffa75dc9493a3ec75519c95355cd1bc8960e1"
