/* automatically generated by rust-bindgen 0.65.1 */

pub const PRPOVER_OK: u32 = 0;
pub const PPROVER_ERROR: u32 = 1;
pub const PPROVER_ERROR_SHORT_BUFFER: u32 = 2;
extern "C" {
    #[doc = " @return error code:\n         PRPOVER_OK - in case of success.\n         PPROVER_ERROR - in case of an error."]
    pub fn groth16_prover(
        zkey_buffer: *const ::std::os::raw::c_void,
        zkey_size: ::std::os::raw::c_ulong,
        wtns_buffer: *const ::std::os::raw::c_void,
        wtns_size: ::std::os::raw::c_ulong,
        proof_buffer: *mut ::std::os::raw::c_char,
        proof_size: *mut ::std::os::raw::c_ulong,
        public_buffer: *mut ::std::os::raw::c_char,
        public_size: *mut ::std::os::raw::c_ulong,
        error_msg: *mut ::std::os::raw::c_char,
        error_msg_maxsize: ::std::os::raw::c_ulong,
    ) -> ::std::os::raw::c_int;
}
