name: "Rust setup"

description: Install stable toolchain fo Rust

runs:
  using: composite
  steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: "rustfmt, clippy"
        toolchain: 1.75.0